//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int question_id { get; set; }
        public string question1 { get; set; }
        public string question_img { get; set; }

        public bool isSelected1  { get; set; }
    public bool isSelected2 { get; set; }
public bool isSelected3  { get; set; }
        public bool isSelected4 { get; set; }
        public Nullable<int> answer_id { get; set; }
        public Nullable<int> true_ans_id { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual TrueAnswer TrueAnswer { get; set; }
    }
}
